services:
  mongo-db:
    container_name: mongo-db
    image: mongo:6
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      # MONGO_INITDB_DATABASE: shopper_db
    volumes:
      # - ./data/:/data/db/
      - /etc/timezone:/etc/timezone:ro

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017/

  shopper-api:
    container_name: shopper-api
    build: ./shopper-backend
    image: shopper-api
    depends_on:
      - mongo-db
    ports:
      - 8080:8080
    environment:
      DB_HOST: mongo-db
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: test
      JWT_SECRET: "jwt_secret"
      SECRET: "secret"
      SERVER_URL: "http://localhost:8080"
      # GEMINI_API_KEY: "api_key" #remove
    links:
      - mongo-db
    volumes:
      - ./images:/images:rw
      - ./logs:/logs:rw
volumes:
  mongo-db:
    driver: local
